# -*- coding: utf-8 -*-
"""NewtonRaphson.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MAUe6w8DBinswFCFz9JoaEsNop0AJrBv
"""

import torch

x=torch.tensor([0.5],dtype=torch.float64,requires_grad=True)

def func(t):
  return t-torch.cos(t)

def newton_raphson(funct,root,steps=10):
  for i in range(steps):
    y=funct(root)
    y.backward()
    root.data=root.data - (y/root.grad).data
    root.grad.data.zero_()
  return root.data

sol=newton_raphson(func,x,100)
print(sol)

